services:
  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    image: medical-management-api:latest
    container_name: medical-migrate
    restart: "no"
    env_file:
      - .env
    working_dir: /app/app
    entrypoint: []
    command: >
      sh -c "echo '[MIGRATE] Running Alembic...' &&
             alembic --config alembic.ini upgrade head &&
             echo '[MIGRATE] Done.'"
    networks:
      - medical-net

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: medical-management-api:latest
    container_name: medical_api
    restart: unless-stopped
    depends_on:
      - migrate
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - medical-net

networks:
  medical-net:
    driver: bridge